# Parameter Estimation For MNIST Dataset

* Classification for digits "7" and "8" only 
* 70,000 images of handwritten digits 
    * 60,000 training images 
    * 10,000 testing images  
    
    
* Number of samples for TRAINING SET:
    * "7": 6265
    * "8": 5851
    
    
* Number of samples in TESTING SET:
    * "7": 1028
    * "8": 974
    
    
* Features
    * Average of ALL pixel values in image
    * Standard Deviation of all pixel values in image

* PROGRAMMER: Francis Mendoza
* ASUID: 1213055998

In [8]:
#UNUSED CODE LINES

#filepath = 'mnist.data_mat'
#data = pd.read_mat(filepath)

#Number_df = pd.DataFrame(np.hstack((Numpyfile['X'], Numpyfile['Y'])))

In [9]:
#Extract Data Set

from __future__ import print_function
import statistics 

import os
import scipy.io
import numpy as np
import pandas as pd 

#import matplotlib.pyplot as plt
#%matplotlib inline
#from skimage.io import imread, imshow

#Import the relevant data using the filepath
Numpyfile= scipy.io.loadmat('mnist_data.mat') 
    #Dictionary 
    
#Display the NumpyFile to check four matrices 
Numpyfile

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Wed Sep 11 18:23:31 2019',
 '__version__': '1.0',
 '__globals__': [],
 'trX': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'trY': array([[0., 0., 0., ..., 1., 1., 1.]]),
 'tsX': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'tsY': array([[0., 0., 0., ..., 1., 1., 1.]])}

In [21]:
trX_array = Numpyfile['trX']
trX_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
Numpyfile['trY']

array([[0., 0., 0., ..., 1., 1., 1.]])

In [22]:
tsX_array = Numpyfile['tsX']
tsX_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
Numpyfile['tsY']

array([[0., 0., 0., ..., 1., 1., 1.]])

In [31]:
#Checking length
    #6265 + 5851 = 12116
    #1028 + 974 = 2002

#REPRESENTS POINTS
print("trX dimensions: "+ str(Numpyfile['trX'].shape))
print("tsX dimensions: "+ str(Numpyfile['tsX'].shape))

#LABELS FOR RESPECTIVE SETS
print("trY dimensions: "+ str(Numpyfile['trY'].shape))
print("tsY dimensions: "+ str(Numpyfile['tsY'].shape))

trX dimensions: (12116, 784)
tsX dimensions: (2002, 784)
trY dimensions: (1, 12116)
tsY dimensions: (1, 2002)


In [34]:
#Feature Selection
"""
REMEMBER: Feature selection is extremely importantby ensuring you are paying attention to
the right features 
    
Paying attention to irrelevant or partially relevant features can negatively impact model performance
"""    
trX_new = []
tsX_new = []

sum = 0
counter = 0

#Nested loop to iterate through numpy array of lists
for i in Numpyfile['trX']:
    mean_temp = statistics.mean(i)
    trX_new += [mean_temp]
    
trX_new

[0.12653061224489795,
 0.07875650260104042,
 0.10974889955982393,
 0.06320028011204482,
 0.1397859143657463,
 0.10207082833133253,
 0.11668667466986794,
 0.09305722288915566,
 0.12973189275710284,
 0.09080132052821129,
 0.11726690676270508,
 0.09603841536614646,
 0.12204381752701081,
 0.06845238095238096,
 0.11201480592236895,
 0.0897358943577431,
 0.07852140856342538,
 0.1531812725090036,
 0.14396758703481394,
 0.13393857543017207,
 0.13895058023209284,
 0.08026210484193677,
 0.13770508203281312,
 0.1270108043217287,
 0.09307222889155663,
 0.12153361344537815,
 0.07718587434973989,
 0.1348889555822329,
 0.09227691076430572,
 0.11144457783113246,
 0.11148459383753502,
 0.09904461784713886,
 0.1267406962785114,
 0.13261304521808723,
 0.11386554621848739,
 0.12397458983593437,
 0.11049919967987196,
 0.08836034413765506,
 0.13447879151660663,
 0.14874949979991997,
 0.10249599839935974,
 0.11259503801520608,
 0.11439575830332133,
 0.07518507402961185,
 0.183718487394958,
 0.069372749099639

In [39]:
#Feature Selection
"""
REMEMBER: Feature selection is extremely importantby ensuring you are paying attention to
the right features 
    
Paying attention to irrelevant or partially relevant features can negatively impact model performance
""" 

""" 
trX_new2 = []
tsX_new = []

#Nested loop to iterate through numpy array of lists
for i in Numpyfile['trX']:
    #Ensure that sum and counter are EACH under loop to restart
    sum2 = 0
    counter2 = 0

    for j in i:
        sum2 += j
        counter2 += 1
    row_mean2 = sum2/counter2
    trX_new2 += [row_mean2]
    
trX_new2
""" 

" \ntrX_new2 = []\ntsX_new = []\n\n#Nested loop to iterate through numpy array of lists\nfor i in Numpyfile['trX']:\n    #Ensure that sum and counter are EACH under loop to restart\n    sum2 = 0\n    counter2 = 0\n\n    for j in i:\n        sum2 += j\n        counter2 += 1\n    row_mean2 = sum2/counter2\n    trX_new2 += [row_mean2]\n    \ntrX_new2\n"

In [ ]:
#Provision Training and Testing Data

    #Access 7
    
    #Access 8

# PART 1: Extract Features & Estimate Parameters
* Estimate parameters for 2D normal distribution for EACH DIGIT using training data
* Two distributions- one for each digit 
* MLE Density Estimation


* Features
    * Average of ALL pixel values in image
    * Standard Deviation of all pixel values in image
    
    
* DELIVER
    * Extract features for both TRAINING and TESTING set
    * Parameter estimation

# PART 2: Naive Bayes using Estimated Distributions
* Report classification accuracy for "7" and "8"
* Produce predicted label for each testing sample


* DELIVER
    * Predicted Labels
    * Classification accuracy for "7" and "8"

# PART 3: Logistic Regression using Gradient Ascent
* Report classification accuracy for "7" and "8"
* Produce predicted label for each testing sample
* (!!!) GRADIENT ASCENT MUST BE DONE FROM SCRATCH


* DELIVER
    * Predicted Labels
    * Classification accuracy for "7" and "8"